import React, { useEffect, useState } from "react";
import IntroOverlay from "../components/introOverlay";
import SectionPara from "../components/sectionPara";
import SectionParaLeft from "../components/sectionParaLeft";
import Path from "../assets/audi.webp";

import gsap from "gsap";
import ProjectTitle from "../components/projectTitle";
import ProjectIntro from "../components/projectIntro";
import FullWidthImage from "../components/fullWidthImage";
import Footer from "../components/footer";
import Hero from "../assets/trickle/hero.png";
import States from "../assets/ewe/states.png";
import Statesgif from "../assets/ewe/states.gif";

import Logistics from "../assets/ewe/logistics.png";
import Amundsen from "../assets/ewe/Amundsen.png";
import Marketing from "../assets/ewe/marketing.png";


import WideImage from "../components/wideImage";
import TallImage from "../components/tallImage";
import Video from "../components/video";
import Sticky from "../components/sticky";

let tl = gsap.timeline();


const intro = { title: 'Amundsen', subtitle: 'A cutting-edge data based joint venture in the energy domain', imageurl:Amundsen};
const introText = { brief: ' Create a user-centred platform which leverages the energy data generated by their customers and provides convenient data solutions – often enabled by Amundsen’s B2B partners in different industries.', intro: 'Founded in 1943, EWE is one of the largest energy supply company in Germany. With the more widespread adoption of Smart Meters and smart appliances, the company came to us for for designing a data-based cutting edge joint venture in the energy market.', company:'ewe'};
const sectioin0 = { num: '', title: 'Clean lines, vibrant colours and ',title1:'fluid motion.', text: 'The Amundsen App makes information intuitive and beautiful. The clean copy and icons are designed to communicate the status of energy and related appliances with a single glance to the users. We used vibrant colours and fluid motion to direct the users to any specific issue or tasks.'};
const sectioin5 = { num: 'USECASE 01', title: 'targeted Marketing.', text: ' To try it out, we included users in the development process, reaching to them in two key stages of the project: At the beginning, through interviews, to find out about their habits and expectations. At a more advanced stage of the visual and Ux design, to confirm that the visual language and the functional focus were as expected. By listening to the real thing, we were able to confirm that we were going in the right direction, and were able to correct and modify some issues as a result of their suggestions.', imageurl:Marketing};
const sectioin6 = { num: 'USECASE 02', title: 'Logistics.', text: ' To try it out, we included users in the development process, reaching to them in two key stages of the project: At the beginning, through interviews, to find out about their habits and expectations. At a more advanced stage of the visual and Ux design, to confirm that the visual language and the functional focus were as expected. By listening to the real thing, we were able to confirm that we were going in the right direction, and were able to correct and modify some issues as a result of their suggestions.', imageurl:Marketing};
const sectioin7 = { num: 'USECASE 03', title: 'Elderly Care.', text: ' To try it out, we included users in the development process, reaching to them in two key stages of the project: At the beginning, through interviews, to find out about their habits and expectations. At a more advanced stage of the visual and Ux design, to confirm that the visual language and the functional focus were as expected. By listening to the real thing, we were able to confirm that we were going in the right direction, and were able to correct and modify some issues as a result of their suggestions.', imageurl:Marketing};

const sectioin1 = { num: '01', title: 'The Home Pulse.', text: ' To try it out, we included users in the development process, reaching to them in two key stages of the project: At the beginning, through interviews, to find out about their habits and expectations. At a more advanced stage of the visual and Ux design, to confirm that the visual language and the functional focus were as expected. By listening to the real thing, we were able to confirm that we were going in the right direction, and were able to correct and modify some issues as a result of their suggestions.'};
const sectioin2 = { num: '02', title: 'Stay in Control', text: 'Users are at the centre of our work. Our main focus is their expeestions.'};
const sectioin3 = { num: '03', title: 'Investigate and Act', text: ' so thsfying and fulfilncluded users in the development process, reaching to them in two key stages of the project: At the beginning, through interviews, to find out about their habits and expectations. At a more advanced stage of the visual and Ux design, to confirm that the visual language and the functional focus were as expected. By listening to the real thing, we were able to confirm that we were going in the right direction, and were able to correct and modify some issues as a result of their suggestions.'};
const sectioin4 = { num: '04', title: 'Share Data When You Gain Insights', text: ' so thsfying and fulfilncluded users in the development process, reaching to them in two key stages of the project: At the beginning, through interviews, to find out about their habits and expectations. At a more advanced stage of the visual and Ux design, to confirm that the visual language and the functional focus were as expected. By listening to the real thing, we were able to confirm that we were going in the right direction, and were able to correct and modify some issues as a result of their suggestions.'};

const homeAnimation = completeAnimation => {
  tl.to(".overlay-top", 1, {
      height: 0,
      ease: "expo.inOut"    })

   
};

const Ewe = ({ dimensions }) => {
  const [animationComplete, setAnimationComplete] = useState(false);

  const completeAnimation = () => {
    setAnimationComplete(true);
  };

  useEffect(() => {
    homeAnimation(completeAnimation);
  }, []);

  useEffect(() => {
    let vh = dimensions.height * 0.01;
    document.documentElement.style.setProperty("--vh", `${vh}px`);
  }, [dimensions.width]);

  return (
    <>
      {animationComplete === false ? <IntroOverlay /> : ""}
      <ProjectTitle intro={intro} />

      <ProjectIntro introText = {introText} />
      <Video />
      <SectionPara section={sectioin0} />
      <div className='ewe-wide-image'>
        <img className ="normal-image"
              src={States}
            />
            <img className ="gif-image"
              src={Statesgif}
            />
      </div>

      <div className="CaptionPayPal">
      The redesigned Summary page focused on putting Activity, balance and linked accounts in the forefront.    
        </div>
        <div className="sectionBold">

        <div className ="sectionTitleBold" > Simplifying management of electrical appliances.</div>
        <div className ="sectionTitleText" > Amundsen acts as a hub for users to manage all his electrical appliances and stay on top of their energy usage.</div>
      </div>
      
        <SectionPara section={sectioin1} />
        <TallImage path={Statesgif}  />


      <SectionParaLeft section={sectioin2}/>
        
      <WideImage path={States}  />

       
        <SectionPara section={sectioin3}/>
        <WideImage path={States}  />

        <SectionParaLeft section={sectioin4}/>
        <WideImage path={States}  />

        <SectionPara section={sectioin5} />
        <TallImage path={Statesgif}  />


      <SectionParaLeft section={sectioin6}/>
        
      <WideImage path={States}  />

       
        <SectionPara section={sectioin7}/>
        <WideImage path={States}  />


        <Footer />


    </>
  );
};

export default Ewe;
