import React, { useEffect, useState } from "react";
import IntroOverlay from "../components/introOverlay";
import SectionPara from "../components/sectionPara";
import SectionParaLeft from "../components/sectionParaLeft";
import Path from "../assets/crowded/hero.jpg";
import HeroVideo from "../assets/ewe/home.mp4";

import gsap from "gsap";
import ProjectTitle from "../components/projectTitle";
import ProjectIntro from "../components/projectIntro";
import FullWidthImage from "../components/fullWidthImage";
import Footer from "../components/footer";
import Hero from "../assets/ewe/hero.jpg";
import States from "../assets/ewe/states.png";
import Statesgif from "../assets/ewe/states.gif";
import Controlgif from "../assets/ewe/control.gif";

import Share from "../assets/ewe/sharer.jpg";
import Investigate from "../assets/ewe/investigate.jpg";

import Logistics from "../assets/ewe/logistics.jpg";
import Amundsen from "../assets/ewe/Amundsen.png";
import Marketing from "../assets/ewe/marketing.jpg";


import WideImage from "../components/wideImage";
import TallImage from "../components/tallImage";
import Video from "../components/video";
import Sticky from "../components/sticky";

let tl = gsap.timeline();


const intro = { title: 'Amundsen', subtitle: 'A cutting-edge data based joint venture in the energy domain', imageurl:Amundsen};
const introText = { brief: ' Create a user-centred platform which leverages the energy data generated by their customers and provides convenient data solutions – often enabled by Amundsen’s B2B partners in different industries.', intro: 'Founded in 1943, EWE is one of the largest energy supply company in Germany. With the more widespread adoption of Smart Meters and smart appliances, the company came to us for designing a data-based cutting edge joint venture in the energy market.', client:'Client',company:'EWE', when: 'Jun 2019 - Aug 2019', what:'I worked as a product designer, focusing on UX and animation design.' };
const sectioin0 = { num: '', title: 'Clean lines, vibrant colours and fluid motion',title1:'fluid motion.', text: 'The Amundsen App makes information intuitive and beautiful. The clean copy and icons are designed to communicate the status of energy and related appliances with a single glance to the users. We used vibrant colours and fluid motion to direct the users to any specific issue or tasks.'};
const sectioin5 = { num: 'USECASE 01', title: 'Targeted Marketing.', text: 'Amundsen can allow businesses to create specific services based on users usage and situation. For example, based on the status of users washing machine, the manufacturer can create speciific offerrrs and target specific users. ', imageurl:Marketing};
const sectioin6 = { num: 'USECASE 02', title: 'Logistics.', text: 'Another use-case we proposed was simplifying logistical delivery for business and consumers based on their general availability.', imageurl:Marketing};
const sectioin7 = { num: 'USECASE 03', title: 'Elderly Care.', text: ' To try it out, we included users in the development process, reaching to them in two key stages of the project: At the beginning, through interviews, to find out about their habits and expectations. At a more advanced stage of the visual and Ux design, to confirm that the visual language and the functional focus were as expected. By listening to the real thing, we were able to confirm that we were going in the right direction, and were able to correct and modify some issues as a result of their suggestions.', imageurl:Marketing};
const sectioin1 = { num: '', title: 'The Home Pulse.', text: ' The home pulse informs the users the status of their different appliances in an intuitive way. Using a intuitive colour scheme user knows whether everything is fine or if there is anything that requires their attention.'};
const sectioin2 = { num: '', title: 'Users stay in Control', text: 'The dashboard is dynamic that prioritises information that needs users atttention while allowing them to access all functionalities.'};
const sectioin3 = { num: '', title: 'Investigate and Act', text: ' Amundsen allows users to track the status of different appliances and perform specific actions based on the current status.'};
const sectioin4 = { num: '', title: 'Full transparency to encourage data sharing', text: 'One of the goal for Amundsen is to build a data market on top of which new services can be built. For that new user data is needed, and Amundsen gets users to share data by first being transparent, and second by offering them tailored value for every data they share.'};
const footerpath = { title: 'next project', text: 'Nubitalk', link:'/nubitalk' };

const homeAnimation = completeAnimation => {
  tl.to(".overlay-top", 1, {
      height: 0,
      ease: "expo.inOut"    })

   
};

const Ewe = ({ dimensions }) => {
  const [animationComplete, setAnimationComplete] = useState(false);

  const completeAnimation = () => {
    setAnimationComplete(true);
  };

  useEffect(() => {
    homeAnimation(completeAnimation);
  }, []);


  return (
    <>
      {animationComplete === false ? <IntroOverlay /> : ""}
      <ProjectTitle intro={intro} />

      <ProjectIntro introText = {introText} />
      <Video path={HeroVideo} />
    

      <SectionPara section={sectioin0}/>
        <FullWidthImage path={Hero}  />
      

      
        <div className="sectionBold">
        <div className="sectionTitleNumber" > 01.</div>

        <div className ="sectionTitleBold" > Users in Control.</div>
        <div className ="sectionTitleText" > Amundsen acts as a hub for users to siimplify the management of all their electrical appliances and stay on top of their energy usage.</div>
      </div>
      <SectionParaLeft section={sectioin4}/>
        <WideImage path={Share}  />
      <div className="sectiom-with-tall-image">
        <div className="sectiom-with-tall-image-firrst">
        <SectionParaLeft section={sectioin1} />

        </div>
        <div className="sectiom-with-tall-image-second">
        <TallImage path={Statesgif}  />

        </div>
        </div>s
      <TallImage path={Controlgif}  />

        <SectionPara section={sectioin2} />

      



       
        <SectionPara section={sectioin3}/>
        <FullWidthImage path={Investigate}  />

       
        <div className="sectionBoldSecond">
        <div className="sectionTitleNumber" > 02.</div>

        <div className="sectionTitleBold" > Business value for Partners.</div>
        <div className="sectionTitleText" > We prototyped many services which could be built on top of the Amundsen platform and creates value for  partners across different industries.</div>
      </div>
        <Sticky content={sectioin5} />



      <SectionParaLeft section={sectioin6}/>
        
      <FullWidthImage path={Logistics}  />



      <Footer path = {footerpath}/>


    </>
  );
};

export default Ewe;
